<template>
  <div>
            <!-- <Head>
                <title>Products | {singleProduct}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head> -->

            <main class="mt-10">
                <div
                    class="font-bold tracking-wide mb-14 mx-p-w font-lato text-bg-primary"
                    style=" font-size: 10px "
                >
                    <router-link to="/">
                        <span class="cursor-pointer hover:underline">Home</span>
                    </router-link>
                    <span class="mx-2">/</span>
                    <router-link to="/">
                        <span class="cursor-pointer hover:underline">Clothings</span>
                    </router-link>
                    <span class="mx-2">/</span>
                    <span class="text-xs">{{singleProduct}}</span>
                </div>

                <!-- {/* single product details */} -->
                <div class="flex md:flex-nowrap flex-wrap mb-20 mx-5 md:mx-p-w gap-14">
                    <div class="flex flex-col" style=" width: 400px ">
                        <!-- {/* <div style={{ height: 266 }}> */} -->
                        <div>
                          <!-- <carousel class="hidden md:block mb-2" :autoplay="1000" :wrapAround="true" :items-to-show="1.2"> -->
    <!-- <slide v-for="image in images" :key="image"> -->
      <img class="object-cover w-full h-72 rounded-lg" :src="images" :alt="singleProduct">
    <!-- </slide> -->

    <!-- <template #addons>
      <navigation />
      <pagination />
    </template> -->
  <!-- </carousel> -->


  <!-- <carousel class="md:hidden mb-2" :autoplay="1000" :wrapAround="true" :items-to-show="1"> -->
    <!-- <slide v-for="image in images" :key="image"> -->
      <!-- <img class="object-cover w-full h-72" :src="images" :alt="singleProduct"> -->
    <!-- </slide> -->

    <!-- <template #addons>
      <navigation />
      <pagination />
    </template> -->
  <!-- </carousel> -->
                        </div>

                        <div
                            class="flex items-center gap-2"
                            style=" height: 29px, margin-top: 29px "
                        >
                            <span
                                class="mr-2 font-normal tracking-wide font-lato"
                                style=" color: #121212, font-size: 8px "
                            >
                                Share
                            </span>
                            <img
                                src="/linkedin-icon.svg"
                                alt="linkedin-icon"
                                class="cursor-pointer"
                            />
                            <img
                                src="/twitter-icon.svg"
                                alt="twitter-icon"
                                class="cursor-pointer"
                            />
                            <img
                                src="/facebook-icon.svg"
                                alt="facebook-icon"
                                class="cursor-pointer"
                            />
                            <img
                                src="/whatsapp-icon.svg"
                                alt="whatsapp-icon"
                                class="cursor-pointer"
                            />
                        </div>
                    </div>

                    <div class="flex flex-col flex-1">
                        <span
                            style=" color: '#4D4D4D'; font-size: 9px; margin-bottom: 6px "
                            class="font-normal font-poppins"
                        >
                            SKU 12314124124
                        </span>

                        <span class="text-sm font-bold tracking-wide text-bg-primary">
                            {{singleProduct}}
                        </span>

                        <div class="flex flex-col md:flex-row items-start md:space-y-0 space-y-3 mt-4 mb-8">
                            <div class="flex items-center">
                                <span
                                    class="mr-2 font-black font-lato"
                                    style=" font-size: 9px; color: #A1E887 "
                                >
                                    4.0
                                </span>
                                    <img v-for="(star,index) in stars" :key="index"
                                        src="/star-green.svg"
                                        alt="star"
                                        style=" marginTop: -2px "
                                    />
                                <span
                                    class="ml-1 font-normal font-lato"
                                    style=" color: #BABABA; font-size: 9px "
                                >
                                    (223)
                                </span>
                            </div>

                            <div
                                class="flex items-center gap-1 md:px-2 md:mx-2 md:border border-t-0 border-b-0"
                                style=" border-color: #F2F2F2 "
                            >
                                <img src="/tick-icon.svg" alt="icon" />
                                <span
                                    class="font-bold font-lato"
                                    style=" color: '#121212', font-size: 9 "
                                >
                                    4,320
                                </span>
                                <span
                                    class="font-normal font-lato"
                                    style=" color: #121212; font-size: 9px "
                                >
                                    Sold
                                </span>
                            </div>

                            <div class="flex items-center flex-1 gap-1">
                                <img src="/eye-icon.svg" alt="icon" />
                                <span
                                    class="font-bold font-lato"
                                    style=" color: #121212; font-size: 9px "
                                >
                                    1.4k
                                </span>
                                <span
                                    class="font-normal font-lato"
                                    style=" color: #121212; font-size: 9px "
                                >
                                    Viewed
                                </span>
                            </div>

                            <div class="flex items-center gap-3 cursor-pointer">
                                <img src="/heart-icon.svg " alt="icon" />
                                <span
                                    class="font-bold tracking-wide font-lato"
                                    style=" color: #A1E887; font-size: 9px "
                                >
                                    Add to wishlist
                                </span>
                            </div>
                        </div>

                        <div class="flex flex-col md:flex-row space-y-3 md:space-y-0 items-start md:items-center">
                            <span
                                class="text-lg font-semibold uppercase font-poppins"
                                style=" color: #A1E887 "
                            >
                                bdt 100
                            </span>
                            <div class="flex flex-1 gap-2 md:ml-3">
                                <span
                                    class="line-through uppercase"
                                    style=" color: #8D8D8D; font-size: 10px "
                                >
                                    bdt 1000
                                </span>
                                <span
                                    class="flex items-center justify-center w-6 font-semibold text-white rounded font-poppins"
                                    style="
                                        font-size: 7px;
                                        background-color: #3AB137;
                                    "
                                >
                                    20%
                                </span>
                            </div>
                            <div>
                                <img src="/logo.svg" alt="logo" />
                            </div>
                        </div>

                        <div
                            class="flex flex-col font-normal tracking-wide border-t-2 font-lato pr-52 pt-7 my-7"
                            style=" border-color:#EAEAEA; font-size: 10px "
                        >
                            <span>
                                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dicta
                                reprehenderit, officia itaque odit reiciendis velit iusto. Labore
                                repellendus inventore quaerat?
                            </span>

                            <div class="flex flex-col gap-6 mt-6">

                                         <span v-html="features" class="capitalize"></span>
                            </div>
                        </div>

                        <div class="flex flex-col md:flex-row md:items-center justify-between mb-10">
                            <span class="text-sm font-bold font-lato mb-2 md:mb-0">Screen Size</span>

                            <div class="flex flex-col md:flex-row gap-3">
                                <span
                                    class="flex items-center justify-center px-5 font-bold border rounded-md cursor-pointer h-9 font-lato"
                                    style="
                                        border-color: #FFEADE;
                                        color: #7B7B7B;
                                        font-size: 10px
                                    "
                                >
                                    14-Inch
                                </span>
                                <span
                                    class="flex items-center justify-center px-5 font-bold rounded-md cursor-pointer text-bg-primary h-9 font-lato"
                                    style="
                                        font-size: 10px;
                                        background-color: #A1E887
                                    "
                                >
                                    24-Inch
                                </span>
                                <span
                                    class="flex items-center justify-center px-5 font-bold border rounded-md cursor-pointer h-9 font-lato"
                                    style="
                                        border-color: #FFEADE;
                                        color: #7B7B7B;
                                        font-size: 10px;
                                    "
                                >
                                    32-Inch
                                </span>
                                <span
                                    class="flex items-center justify-center px-5 font-bold border rounded-md cursor-pointer h-9 font-lato"
                                    style="
                                        border-color: #FFEADE;
                                        color: #7B7B7B;
                                        font-size: 10px;
                                    "
                                >
                                    60-Inch
                                </span>
                            </div>
                        </div>

                        <div class="flex flex-wrap md:flex-nowrap justify-between">
                            <div
                                class="flex md:mx-0 mx-auto items-center gap-10 px-3 border rounded-md h-9"
                                style=" border-color: #D8D8D8 "
                            >
                                <span class="cursor-pointer" @click="quantity--">
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="9.5"
                                        height="2"
                                        viewBox="0 0 9.5 2"
                                    >
                                        <rect
                                            id="_-"
                                            data-name="-"
                                            width="9.5"
                                            height="2"
                                            fill="#d2d2d2"
                                        />
                                    </svg>
                                </span>
                                <span
                                    class="font-bold text-bg-primary font-lato"
                                    style=" font-size: 10px "
                                >
                                    {{quantity}}
                                </span>
                                <span class="cursor-pointer" @click="quantity++">
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="8.784"
                                        height="9.045"
                                        viewBox="0 0 8.784 9.045"
                                    >
                                        <path
                                            id="_"
                                            data-name="+"
                                            d="M3788.783,558.443v3.69h3.5v1.647h-3.5v3.708h-1.8V563.78H3783.5v-1.647h3.483v-3.69Z"
                                            transform="translate(-3783.5 -558.443)"
                                            fill="#d2d2d2"
                                        />
                                    </svg>
                                </span>
                            </div>

                            <div class="flex md:mx-0 mt-2 md:mt-0 mx-auto gap-2">
                                <span
                                    class="flex items-center font-bold uppercase border rounded-md cursor-pointer px-9 h-9 text-bg-primary font-lato"
                                    style=" border-color: #D8D8D8; font-size: 10px "
                                >
                                    buy
                                </span>
                                <span @click="addToCart"
                                    class="flex items-center justify-center w-32 font-bold text-white uppercase rounded-md cursor-pointer bg-bg-primary font-lato h-9"
                                    style=" font-size: 10px "
                                >
                                    add to cart
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- {/* single product review */} -->
                <div class="flex flex-col md:flex-row justify-between mb-20 mx-5 md:mx-p-w">
                    <div
                        class="flex flex-col items-center px-6 py-10 text-white rounded-md bg-bg-primary"
                        style=" max-height: 478px "
                    >
                        <div>
                            <span class="font-semibold font-poppins" style=" font-size: 50px ">
                                4.0
                            </span>
                            <span
                                style=" color: #70606F "
                                class="text-xs font-semibold font-poppins"
                            >
                                /5
                            </span>
                        </div>

                        <div class="flex gap-2 mt-1 mb-3">
                                <span v-for="(star,index) in stars" :key="index">
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="17.227"
                                        height="15.661"
                                        viewBox="0 0 17.227 15.661"
                                    >
                                        <path
                                            id="star"
                                            d="M3342.589,759.045l-2.1,4.049-4.7.651a.967.967,0,0,0-.57,1.67l3.4,3.15-.8,4.45a1.02,1.02,0,0,0,1.494,1.031l4.209-2.1,4.208,2.1a1.021,1.021,0,0,0,1.494-1.031l-.8-4.45,3.4-3.15a.967.967,0,0,0-.57-1.67l-4.7-.651-2.1-4.049A1.056,1.056,0,0,0,3342.589,759.045Z"
                                            transform="translate(-3334.9 -758.5)"
                                            fill="#ebff00"
                                        />
                                    </svg>
                                </span>
                        </div>

                        <div
                            class="font-normal tracking-wide font-poppins"
                            style=" font-size: 10px "
                        >
                            223 Reviews
                        </div>

                        <div class="flex flex-col gap-6 mt-12">
                                <div v-for="item in starCount" :key="item.star" class="flex flex-col w-40 gap-2">
                                    <div class="flex items-center justify-between">
                                        <div class="flex gap-1">
                                            
                                                <span v-for="(item,index) in item.star" :key="index">
                                                    <svg
                                                        xmlns="http://www.w3.org/2000/svg"
                                                        width="8"
                                                        height="7"
                                                        viewBox="0 0 8 7"
                                                    >
                                                        <path
                                                            id="star"
                                                            d="M3329.071,845.744l-.976,1.81-2.185.291a.429.429,0,0,0-.264.746l1.58,1.408-.374,1.989a.471.471,0,0,0,.694.461l1.954-.939,1.955.939a.471.471,0,0,0,.694-.461l-.374-1.989,1.58-1.408a.429.429,0,0,0-.265-.746l-2.185-.291-.977-1.81A.5.5,0,0,0,3329.071,845.744Z"
                                                            transform="translate(-3325.5 -845.5)"
                                                            fill="#fff"
                                                        />
                                                    </svg>
                                                </span>
                                        </div>
                                        <span
                                            class="font-normal tracking-wide font-poppins"
                                            style=" font-size: 9px "
                                        >
                                            {{item.count}}
                                        </span>
                                    </div>
                                    <div>
                                        <div
                                            style="
                                                height: 5px;
                                                border-radius: 2.5px;
                                                background-color: #70606F;
                                            "
                                            class="relative w-full"
                                        >
                                            <div
                                                class="absolute top-0 bottom-0 left-0 bg-white"
                                                :style="{
                                                    borderRadius: '2.5px',
                                                    width: (item.count * 100) / 223 + '%'
                                                    }"
                                            />
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>

                    <div class="flex-1" style=" max-width: 950px ">
                        <div
                            style=" background-color: #F9F9F9; height: 49px "
                            class="flex md:overflow-none overflow-auto items-center gap-16 px-10 rounded-md"
                        >
                            <span
                                class="relative flex items-center h-full text-xs font-semibold font-poppins"
                                style=" color: #A1E887 "
                            >
                                Description
                                <span class="absolute bottom-0 transform -translate-x-1/2 left-1/2">
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="36"
                                        height="3"
                                        viewBox="0 0 36 3"
                                    >
                                        <path
                                            id="background"
                                            d="M3541.5,696.5h30a3,3,0,0,1,3,3h-36A3,3,0,0,1,3541.5,696.5Z"
                                            transform="translate(-3538.5 -696.5)"
                                            fill="#493548"
                                        />
                                    </svg>
                                </span>
                            </span>
                            <span
                                class="text-xs font-normal cursor-pointer font-poppins"
                                style=" color: #9F9F9F "
                            >
                                Specification
                            </span>
                            <span
                                class="text-xs font-normal cursor-pointer font-poppins"
                                style=" color: #9F9F9F "
                            >
                                Discussion
                            </span>
                            <span
                                class="text-xs font-normal cursor-pointer font-poppins"
                                style=" color: #9F9F9F "
                            >
                                Reviews (223)
                            </span>
                        </div>

                        <div class="flex flex-col gap-16 mt-16 mx-7">
                            <div class="flex flex-col gap-3">
                                <span class="text-xs font-bold font-lato">
                                    See the best picture no matter where you sit
                                </span>
                                <span
                                    class="font-normal font-lato"
                                    style=" color: #454545; font-size: 9px "
                                >
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                                    eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                                    enim ad minim veniam, quis nostrud exercitation ullamco laboris
                                    nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                                    in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                                    nulla pariatur. Excepteur sint occaecat cupidatat non proident,
                                    sunt in culpa qui officia deserunt mollit anim id est laborum
                                </span>
                            </div>

                            <div
                                class="flex justify-end px-12 py-8 mb-7"
                                style=" background-color: #C4C4C4 "
                            >
                                <div
                                    class="flex flex-col flex-1 gap-5 text-right text-white"
                                    style=" max-width: 176px "
                                >
                                    <span class="text-2xl font-medium tracking-wide font-poppins">
                                        Your new home office
                                    </span>
                                    <span
                                        class="font-medium tracking-wide font-poppins"
                                        style=" font-size: 9px "
                                    >
                                        Remote Acess
                                    </span>
                                    <span
                                        class="font-light tracking-wide font-lato"
                                        style=" font-size: 8 "
                                    >
                                        Get office work done on your TV at home. Remote Access lets
                                        you mirror your computer’s display on the TV screen
                                        wirelessly.
                                    </span>
                                </div>
                            </div>

                            <div class="flex flex-col gap-3">
                                <span class="text-xs font-bold font-lato">
                                    Powerful intelligence for perfection
                                </span>
                                <span
                                    class="font-normal font-lato"
                                    style=" color: #454545; font-size: 9px "
                                >
                                    Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                                    accusantium doloremque laudantium, totam rem aperiam, eaque ipsa
                                    quae ab illo inventore veritatis et quasi architecto beatae
                                    vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia
                                    voluptas sit aspernatur aut odit aut fugit, sed quia
                                    consequuntur magni dolores eos qui ratione voluptatem sequi
                                    nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor
                                    sit amet, consectetur, adipisci velit, sed quia non numquam eius
                                    modi tempora incidunt ut labore et dolore magnam aliquam quaerat
                                    voluptatem. Ut enim ad minima veniam, quis nostrum
                                    exercitationem ullam corporis suscipit laboriosam, nisi ut
                                    aliquid ex ea commodi consequatur? Quis autem vel eum iure
                                    reprehenderit qui in ea voluptate velit esse quam nihil
                                    molestiae consequatur, vel illum qui dolorem eum fugiat quo
                                    voluptas nulla pariatur?
                                </span>
                            </div>

                            <div class="flex flex-col gap-3">
                                <span class="text-xs font-bold font-lato">
                                    The power of less
                                </span>
                                <span
                                    class="font-normal font-lato"
                                    style=" color: #454545; font-size: 9px "
                                >
                                    At vero eos et accusamus et iusto odio dignissimos ducimus qui
                                    blanditiis praesentium voluptatum deleniti atque corrupti quos
                                    dolores et quas molestias excepturi sint occaecati cupiditate
                                    non provident, similique sunt in culpa qui officia deserunt
                                    mollitia animi, id est laborum et dolorum fuga. Et harum quidem
                                    rerum facilis est et expedita distinctio. Nam libero tempore,
                                    cum soluta nobis est eligendi optio cumque nihil impedit quo
                                    minus id quod maxime placeat facere possimus, omnis voluptas
                                    assumenda est, omnis dolor repellendus. Temporibus autem
                                    quibusdam et aut officiis debitis aut rerum necessitatibus saepe
                                    eveniet ut et voluptates repudiandae sint et molestiae non
                                    recusandae. Itaque earum rerum hic tenetur a sapiente delectus,
                                    ut aut reiciendis voluptatibus maiores alias consequatur aut
                                    perferendis doloribus asperiores repellat
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

                <SeventhPart />
            </main>
        </div>
</template>

<script>
import SeventhPart from '../components/SeventhPart.vue'
import 'vue3-carousel/dist/carousel.css';
// , Pagination, Navigation
// import { Carousel, Slide } from 'vue3-carousel';
import axios from 'axios'

export default {
  components:{
    // Carousel,
    // Slide,
    SeventhPart
  },
data(){
  return{
      daResponse:[],
      quantity:1,
    singleProduct:"",
    stars:4,
    starCount:[
                                { star: 5, count: 186 },
                                { star: 4, count: 18 },
                                { star: 3, count: 12 },
                                { star: 2, count: 5 },
                                { star: 1, count: 2 },
                            ],
    features:[
                                    'direct full array',
                                    'quantum dot technology',
                                    'ambient mode',
                                    'one remote control',
                                ],
    images : [
        'https://i.pinimg.com/564x/c7/f6/bd/c7f6bdef61e2558147339c0057eee2e8.jpg',
        'https://i.pinimg.com/564x/c7/f6/bd/c7f6bdef61e2558147339c0057eee2e8.jpg',
        'https://i.pinimg.com/564x/c7/f6/bd/c7f6bdef61e2558147339c0057eee2e8.jpg',
        'https://i.pinimg.com/564x/c7/f6/bd/c7f6bdef61e2558147339c0057eee2e8.jpg',
        'https://i.pinimg.com/564x/c7/f6/bd/c7f6bdef61e2558147339c0057eee2e8.jpg',
    ]
  }
},
methods:{
    // addToCart(){
    //     axios.get(process.env.VUE_APP_API_URL + "products/" + this.$route.params.id).then((response) => {
    //   let daResponse = response.data.data
    //     this.singleProduct = daResponse.name
    //     this.features = daResponse.description
    //     this.images = daResponse.image
    //   }).catch((error) => {
    //     // handle error
    //     console.log(error);
    //   });
    // }
},
mounted(){
//   this.singleProduct = 
  axios.get(process.env.VUE_APP_API_URL + "products/" + this.$route.params.id).then((response) => {
      let daResponse = response.data.data
      this.daResponse = daResponse
        this.singleProduct = daResponse.name
        this.features = daResponse.description
        this.images = daResponse.image
      }).catch((error) => {
        // handle error
        console.log(error);
      });
},
}
</script>

<style>

</style>