<template>
  <div>
        <Head>
            <title>SellBee | Track Order</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="flex flex-col my-12 gap-7 mx-p-w">
            <span className="text-2xl font-semibold font-poppins">Track your order here.</span>

            <div className="flex gap-10 mt-3">
                <div className="flex flex-col flex-1 gap-2">
                    <span className="text-sm font-normal font-lato">Email</span>
                    <input
                        type="text"
                        className="w-full border rounded-md outline-none"
                        style={{ borderColor: '#D4D4D4', height: 57 }}
                    />
                </div>

                <div className="flex flex-col flex-1 gap-2">
                    <span className="text-sm font-normal font-lato">Order ID</span>
                    <input
                        type="text"
                        className="w-full border rounded-md outline-none"
                        style={{ borderColor: '#D4D4D4', height: 57 }}
                    />
                </div>
            </div>

            <button
                type="button"
                className="flex items-center self-end justify-center px-20 py-3 font-bold tracking-wide uppercase rounded-md cursor-pointer bg-bg-primary font-lato"
                style={{ fontSize: 10, color: '#FBFBFB' }}
            >
                track your order
            </button>

            <div
                className="flex p-5 mt-2 border rounded-md gap-60"
                style={{ borderColor: '#D4D4D4' }}
            >
                {/* your order */}
                <div>
                    <div
                        className="mb-4 font-semibold tracking-wide font-poppins"
                        style={{ fontSize: 10 }}
                    >
                        Your Orders
                    </div>

                    <div
                        className="flex flex-col gap-4 pb-5 mb-5 border-b"
                        style={{ borderColor: '#F3F3F3' }}
                    >
                        <div className="flex">
                            <span
                                className="font-semibold font-lato"
                                style={{ color: '#1D1D1D', fontSize: 10 }}
                            >
                                1x
                            </span>
                            <span
                                className="ml-5 font-normal font-lato"
                                style={{ color: '#8D8D8D', fontSize: 9, maxWidth: 132 }}
                            >
                                LED Monitor With High Quality In The World
                            </span>
                            <span
                                className="flex-1 font-semibold text-right font-lato "
                                style={{ color: '#1D1D1D', fontSize: 10 }}
                            >
                                976.33
                            </span>
                        </div>

                        <div className="flex">
                            <span
                                className="font-semibold font-lato"
                                style={{ color: '#1D1D1D', fontSize: 10 }}
                            >
                                1x
                            </span>
                            <span
                                className="ml-5 font-normal font-lato"
                                style={{ color: '#8D8D8D', fontSize: 9, maxWidth: 132 }}
                            >
                                LED Monitor With High Quality In The World
                            </span>
                            <span
                                className="flex-1 font-semibold text-right font-lato "
                                style={{ color: '#1D1D1D', fontSize: 10 }}
                            >
                                976.33
                            </span>
                        </div>
                    </div>

                    <div
                        className="flex flex-col gap-3 pb-5 mb-5 border-b"
                        style={{ borderColor: '#F3F3F3' }}
                    >
                        <div className="flex justify-between">
                            <span
                                className="font-normal font-lato"
                                style={{ color: '#8D8D8D', fontSize: 9 }}
                            >
                                Subtotal
                            </span>
                            <span
                                className="font-semibold font-lato"
                                style={{ fontSize: 10, color: '#1D1D1D' }}
                            >
                                1,952.66
                            </span>
                        </div>

                        <div className="flex justify-between">
                            <span
                                className="font-normal font-lato"
                                style={{ color: '#8D8D8D', fontSize: 9 }}
                            >
                                Shipping
                            </span>
                            <span
                                className="font-semibold font-lato"
                                style={{ fontSize: 10, color: '#1D1D1D' }}
                            >
                                0
                            </span>
                        </div>

                        <div className="flex justify-between">
                            <span
                                className="font-normal font-lato"
                                style={{ color: '#8D8D8D', fontSize: 9 }}
                            >
                                Tax
                            </span>
                            <span
                                className="font-semibold font-lato"
                                style={{ fontSize: 10, color: '#1D1D1D' }}
                            >
                                4.00
                            </span>
                        </div>
                    </div>

                    <div className="flex justify-between">
                        <span
                            className="font-medium tracking-wide font-poppins"
                            style={{ fontSize: 9 }}
                        >
                            Order Total
                        </span>
                        <span className="text-sm font-semibold font-poppins text-bg-primary">
                            1956.66
                        </span>
                    </div>
                </div>

                {/* status */}
                <div className="flex flex-col gap-4 mb-6">
                    <span className="font-semibold font-poppins" style={{ fontSize: 10 }}>
                        Status
                    </span>

                    <div className="flex items-center gap-3">
                        <input type="checkbox" className="cursor-pointer" />
                        <span className="font-normal font-lato" style={{ fontSize: 9 }}>
                            Direct Bank Transfer
                        </span>
                    </div>

                    <div className="flex items-center gap-3">
                        <input type="checkbox" className="cursor-pointer" />
                        <span className="font-normal font-lato" style={{ fontSize: 9 }}>
                            Paypol
                        </span>
                    </div>

                    <div className="flex items-center gap-3">
                        <input type="checkbox" className="cursor-pointer" />
                        <span className="font-normal font-lato" style={{ fontSize: 9 }}>
                            Cash On Delivery
                        </span>
                    </div>
                </div>
            </div>
        </main>
    </div>
</template>

<script>
export default {

}
</script>

<style>

</style>